Update OrangeFox-OFRP.yml

diff --git a/.github/workflows/OrangeFox-OFRP.yml b/.github/workflows/OrangeFox-OFRP.yml
--- a/.github/workflows/OrangeFox-OFRP.yml
+++ b/.github/workflows/OrangeFox-OFRP.yml
@@ -46,7 +46,15 @@ jobs:
       run: |
         git clone https://gitlab.com/OrangeFox/sync.git ~/OrangeFox_sync
         cd ~/OrangeFox_sync
+
         ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
+
+        cd ~/fox_12.1
+        repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
+
+    - name: Verify framework files
+      run: |
+         ls -l ~/fox_12.1/frameworks/base/services/core/xsd/vts/ || echo "Missing folder"
 
     # ✅ Device tree
     - name: Clone device tree
